### ISSUE TITLE
use `http` status codes

### ISSUE THREAD

**Issue by casperdcl** [premAI-io/prem-daemon#116]
Noticed HTTP status codes (e.g. `200`, `400`, etc.) are hard-coded atm. Would be better to use [`http.HTTPStatus`](https://docs.python.org/3/library/http.html#http-status-codes)?

**Comment by tiero** [comment]
Agreed!

**Comment by Janaka-Steph** [comment]
For example replacing `assert response.status_code == 200` with `assert response.status_code == HTTPStatus.OK` ?

**Comment by filopedraz** [comment]
Yes @Janaka-Steph and there are some hard coded values in `routes.py` as well.
