### ISSUE TITLE
Support multiple GPUs

### ISSUE THREAD

**Issue by filopedraz** [premAI-io/prem-daemon#131]
### Description

When fetching system resources, get info from all the GPUs in the system.

**Comment by Janaka-Steph** [comment]
Can we get AMD GPU information requesting `rocminfo` with subprocess like in https://gist.github.com/damico/484f7b0a148a0c5f707054cf9c0a0533 ?

**Comment by filopedraz** [comment]
@Janaka-Steph we can use this [package](https://github.com/anderskm/gputil) in order to handle this issue.

**Comment by Janaka-Steph** [comment]
> @Janaka-Steph we can use this [package](https://github.com/anderskm/gputil) in order to handle this issue.

This is only for NVidia GPUs. What about AMD and Intel?
This issue "Support multiple GPUs" means multiple GPU manufacturers or something else?

**Comment by filopedraz** [comment]
It means return the data (stats) of all the GPUs in the machine. Currently even if the server has 1+ GPU mounted we return only the stats of the first one.

**Comment by tiero** [comment]
The issue is simply that we only recognize one GPU if the machine has multiple smaller GPUs instead of one. (you can try with a `g5.12xlarge` ec2 on AWS) 

This basically does not allow the daemon to run services that go beyond a single GPU, even if it would have been possible with a simple `docker run --gpu all`

**Comment by filopedraz** [comment]
[@sekulicd we are now using `GPUUtils` to get GPUs information. You can check this commit](https://github.com/premAI-io/prem-daemon/pull/141/commits/4a26d98d5d869a86750e18939c4695385623d58a). You first need to change the method `get_gpu_stats` in order to return all the GPUs info.
