### ISSUE TITLE
Support for binaries

### ISSUE THREAD

**Issue by filopedraz** [premAI-io/prem-daemon#132]
### Description

Daemon should be able to run binaries as well. Not only Docker images.

Use `Tabby` as first binary based service: https://tabbyml.github.io/tabby/docs/self-hosting/apple.

**Comment by tiero** [comment]
I would add to the discussion the topic on how we run/stop/monitor process, not only docker container. Nomad is very insteresting as is a orchestrator tool, for anything. Ie. running Python scripts or binaries, would be the same thing.

https://www.nomadproject.io/

**Comment by filopedraz** [comment]
In order to run binaries from daemon, the daemon must be out of Docker. In order to do that we need to create a binary out of the daemon. We should start from #139 and see if there are issues with that.

**Comment by filopedraz** [comment]
@Janaka-Steph I will start investigating Nomad as an alternative for the Daemon.
