### ISSUE TITLE
Download events not ignored

### ISSUE THREAD

**Issue by Janaka-Steph** [premAI-io/prem-daemon#174]
Download events sent to the frontend should ignore those status:
```
 if (
                status == Status.ALREADY_EXISTS.value
                or status == Status.DOWNLOAD_COMPLETE.value
                or status.startswith("Pulling from")
                or status.startswith("Pulling fs layer")
            ):
                continue
```

<img width="1724" alt="Screenshot 2023-11-02 at 08 05 24" src="https://github.com/premAI-io/prem-daemon/assets/4022128/3ba78c06-8fa2-426b-a79d-8373e8614eeb">

**Comment by casperdcl** [comment]
Why? IMO if a user has half the layers, download should start at 50% not 0%.

**Comment by Janaka-Steph** [comment]
Check the previous code and why we ignore some status.
